
name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releaseCreated: ${{ steps.release.outputs.new-release-published }}
      version: ${{ steps.release.outputs.release-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        uses: docker://ghcr.io/codfish/semantic-release-action:latest
        id: release
        with:
          tag_format: 'v${version}'
          branches: |
            [
              'master'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}